log4j.configurationFile=config/log4j2.xml

port = 4004
colorBlue = \u001B[34m
colorRed = \u001B[31m
colorGreen = \u001B[32m
colorDefault = \u001B[0m
jsonFileName = UserJson.json
plainFileName = UserText.txt